In [ ]:
import copy
def knapSack(W, weight, profit, n):
    A = [[0 for x in range(W + 1)] for x in range(n + 1)]
    Sol=[[ [] for x in range(W + 1)] for x in range(n + 1)]

    for i in range(n + 1):
        for w in range(W + 1):  #we look at the i th element,the index in weight and profit array is (i-1)
            if i == 0 or w == 0:
                A[i][w] = 0
            elif weight[i-1] <= w:
                A[i][w] = max(profit[i-1]+ A[i-1][w-weight[i-1]], A[i-1][w]) 
                if A[i-1][w]< profit[i-1]+ A[i-1][w-weight[i-1]]:
                    Sol[i][w]=copy.deepcopy(Sol[i-1][w-weight[i-1]])
                    Sol[i][w].append(i)
                    print(i,w,A[i][w],Sol[i][w],'循环2')
                else:
                    Sol[i][w]=Sol[i-1][w]
                    print(i,w,A[i][w],Sol[i][w],'循环2')
            else:
                A[i][w] = A[i-1][w]
                Sol[i][w]=copy.deepcopy(Sol[i-1][w])   #deepcopy in case it changes (in fact it will) the value of Sol[i-1][w]
                print(i,w,A[i][w],Sol[i][w],Sol[i-1][w],'循环3')


    return A[n][W], Sol[n][W]


# Driver code
val = [2, 5, 7, 8]
wt = [3, 6, 7, 8]
W = 10
n = len(val)
print(knapSack(W, wt, val, n))


# This code is contributed by Bhavya Jain


In [ ]:
import copy
import numpy as np

profit = [2, 5, 7, 8]
weight = [3, 6, 7, 8]
W = 10
n=len(profit)

A = [[0 for x in range(W + 1)] for x in range(n + 1)]
Sol=[[ [] for x in range(W + 1)] for x in range(n + 1)]


for i in range(n + 1):
    for w in range(W + 1):  #we look at the i th element,the index in weight and profit array is (i-1)
        if i == 0 or w == 0:
            A[i][w] = 0
        elif weight[i-1] <= w:
            A[i][w] = max(profit[i-1]+ A[i-1][w-weight[i-1]], A[i-1][w]) 
            if A[i-1][w]< profit[i-1]+ A[i-1][w-weight[i-1]]:
                Sol[i][w]=copy.deepcopy(Sol[i-1][w-weight[i-1]])
                Sol[i][w].append(i)
                #print(i,w,A[i][w],Sol[i][w],'循环2')
            else:
                Sol[i][w]=Sol[i-1][w]
                #print(i,w,A[i][w],Sol[i][w],'循环2')
        else:
            A[i][w] = A[i-1][w]
            Sol[i][w]=copy.deepcopy(Sol[i-1][w])   #deepcopy in case it changes (in fact it will) the value of Sol[i-1][w]
            #print(i,w,A[i][w],Sol[i][w],Sol[i-1][w],'循环3')


print(np.matrix(A))
print(np.matrix(Sol))
    

In [17]:
import numpy as np

profit = [1, 2, 3]
weight = [3, 6, 7]
W= 20
n=len(profit)
P=profit[-1]

C = [[0 for x in range(P + 1)] for x in range(n + 1)]
#Sol=[[ [] for x in range(P + 1)] for x in range(n + 1)]
print(C)

for q in range(n + 1):
    for p in range(P + 1):  #we look at the i th element,the index in weight and profit array is (i-1)
        if p==0 or q==0:
            C[q][p]=0
            print(q, p, C[q][p])
        elif p> sum(profit[:q]):
            C[q][p]= 0
            print('sum')
            print(q, p, C[q][p])   
        else:
            #k=1
            res=weight[q-1]
            if profit[q-1]>p:    #the initail choice has a profit larger than p
                j=q-1
                while profit[j]>p:  
                    j-=1
                res=weight[j]
            
            for k in range(0,q):
            #while q-k>0:
                print('a')
                if p-profit[q-k-1]>=0:  #profit不会出现负数
                    if weight[q-k-1]+C[q-k-1][p-profit[q-k-1]]<res:    
                    #the latter is optimal & the new solution is feasible
                        if weight[q-k-1]+C[q-k-1][p-profit[q-k-1]]<=W:
                            C[q][p]=weight[q-k-1]+C[q-k-1][p-profit[q-k-1]]
                            print('q-k:',q-k, 'weight[q-k-1]:',weight[q-k-1], 'C:', q-k, p-profit[q-k-1],C[q-k-1][p-profit[q-k-1]]) 
            print(q, p, C[q][p])
            #k+=1  may be in the wrong indent
        
                        
print(np.matrix(C))
#print(np.matrix(Sol))

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
0 0 0
0 1 0
0 2 0
0 3 0
1 0 0
a
1 1 0
sum
1 2 0
sum
1 3 0
2 0 0
a
a
2 1 0
a
a
q-k: 1 weight[q-k-1]: 3 C: 1 1 0
2 2 3
a
a
q-k: 1 weight[q-k-1]: 3 C: 1 2 0
2 3 3
3 0 0
a
a
a
3 1 0
a
a
a
q-k: 1 weight[q-k-1]: 3 C: 1 1 0
3 2 3
a
a
q-k: 2 weight[q-k-1]: 6 C: 2 1 0
a
q-k: 1 weight[q-k-1]: 3 C: 1 2 0
3 3 3
[[0 0 0 0]
 [0 0 0 0]
 [0 0 3 3]
 [0 0 3 3]]


In [ ]:
l=[1,3,5]
print(sum(l[:2]))